#!/bin/bash
set -e

# install nginx.conf
cp /app/setup/nginx.conf /etc/nginx/nginx.conf

# configure php5-fpm to listen on unix domain sockets
sed 's,listen = 127.0.0.1:9000,listen = /var/run/php5-fpm.sock,' -i /etc/php5/fpm/pool.d/www.conf
sed 's,;listen.owner = www-data,listen.owner = www-data,' -i /etc/php5/fpm/pool.d/www.conf
sed 's,;listen.group = www-data,listen.group = www-data,' -i /etc/php5/fpm/pool.d/www.conf
sed 's,;listen.mode = 0660,listen.mode = 0660,' -i /etc/php5/fpm/pool.d/www.conf
