#!/bin/bash
set -e

# start supervisord
/usr/bin/supervisord

echo "Starting php5-fpm..."
supervisorctl start php5-fpm >/dev/null

echo "Starting nginx..."
supervisorctl start nginx >/dev/null

tail -F /var/log/nginx/*.log
